name: Go-tip

on:
  schedule:
    # Every Sunday at 13:00
    - cron: "*/5 * * * *"

jobs:
  check:
    name: Checks
    uses: PavelKhripkov/pmm/.github/workflows/common.yml@test
    with:
      go-version: 'tip'
