name: Go-tip

on:
  schedule:
    # Every Sunday at 13:00
    - cron: "*/5 * * * *"

jobs:
  check:
    name: Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/common.yml
        with:
          go-version: 'tip'
